/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MicroBlog } from "./MicroBlog";

export { MicroBlog__factory } from "./factories/MicroBlog__factory";
